version: "3.7"

services:
  rudl_cloudfront:
    image: infracamp/rudl-cloudfront
    deploy:
      mode: global
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - rudl-cf-net
      - rudl-principal-net

  rudl_principal:
    image: infracamp/rudl-principal
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "rudl-principal:/mnt"
    networks:
     - rudl-principal-net

volumes:
  rudl-principal:


networks:
  rudl-cf-net:
    external: true

  rudl-principal-net:
    external: false